name: Build and Test

on: [push, pull_request]

jobs:
  test-ubuntu-macos:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            install-lib: sudo apt-get install --quiet -y libpcre2-dev
          - os: macos-latest
            install-lib: brew install pcre2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
          path: v

      - name: Build V
        run: |
          cd v && make && sudo ./v symlink && cd -

      - name: Install pcre2 library dependency
        run: |
          ${{ matrix.install-lib }}

      - name: Install rimu module and dependencies
        run: |
          v install srackham.rimu

      - name: Install rimu repo and run tests
        run: |
          git clone https://github.com/srackham/v-rimu
          cd v-rimu
          make test

  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
          path: v

      - name: Build V
        run: |
          cd v
          .\make.bat
          .\v.exe symlink

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true

      - name: Install MYSYS2 package mingw-w64-x86_64-pcre2
        run: |
          C:\msys64\usr\bin\pacman.exe -S --noconfirm mingw-w64-x86_64-pcre2

      - name: Install rimu module and dependencies
        run: |
          .\v\v.exe install srackham.rimu

      - name: Install rimu repo and run tests
        run: |
          git clone https://github.com/srackham/v-rimu
          cd v-rimu
          mkdir bin
          ..\v\v.exe -enable-globals -o bin/rimuv.exe cmd/rimuv/rimuv.v
          ..\v\v.exe -enable-globals test .
